### ISSUE TITLE
reset playlistName 

### ISSUE THREAD

**Issue by mp1pro** [albinario/jammming#1]
The reason why the playlistName does not reset when the 'save to spotify' button is clicked is because the value of the input that displays the name has a `default value` instead of `value` attribute;

`<input defaultValue={this.props.playlistName} onChange={this.handleNameChange}/>`

It should be like this instead;

`<input value={this.props.playlistName} onChange={this.handleNameChange}/>`

in playList.js

**Comment by albinario** [comment]
Aah, thanks. Spent a good half day trying to solve that one hehe..
